language: python

python:
  - "2.7"

services:
  - docker

before_install:
  - docker build -t xeonfibre-papermc:latest .
  - bash tests/google-cst/get-cst.sh

install:
  - docker run -d -p 127.0.0.1:25565:25565 xeonfibre-papermc:latest

before_script:
  - docker ps
  - sleep 120
  - docker logs $(docker ps -q)

script:
  - bash tests/google-cst/run-cst.sh
  - python tests/minestat/status-loop.py
  