language: python

services:
  - docker

before_install:
  - docker-compose build --verbose
  - bash tests/google-cst/get-cst.sh

install:
  - docker-compose up -d

before_script:
  - docker ps

script:
  - bash tests/google-cst/run-cst.sh
  - python tests/minestat/status-loop.py
