language: python
sudo: required
services:
  - docker

before_install:
  - docker-compose build
  - bash tests/google-cst/get-cst.sh

install:
  - docker-compose --verbose up -d

before_script:
  - docker ps
  - sleep 120
  - docker-compose logs

script:
  - bash tests/google-cst/run-cst.sh
  - python tests/minestat/status-loop.py
