language: python

services:
  - docker

before_install:
  - docker-compose build
  - bash tests/google-cst/get-cst.sh

install:
  - docker-compose --privileged --verbose up -d

before_script:
  - docker ps
  - sleep 100
  - docker-compose logs

script:
  - bash tests/google-cst/run-cst.sh
  - python tests/minestat/status-loop.py
