language: python

python:
  - "2.7"

services:
  - docker

before_install:
  - docker build --build-arg PAPERMC_VERSION=1.15.2 -t papermc:test .
  - bash tests/google-cst/get-cst.sh

install:
  - docker run -d -p 25565:25565 papermc:test

before_script:
  - docker ps
  - sleep 120
  - docker logs $(docker ps -q)

script:
  - bash tests/google-cst/run-cst.sh
  - python tests/minestat/status-loop.py
  